### ISSUE TITLE
Bonita7

### ISSUE THREAD

**Issue by ajandresitc** [Bonitasoft-Community/Bonita-Examples#1]
hi guys... I used your example in bonita 7.0.1 version, i have other process whith mysql conector, i tried to do the same copy the process and it doesn't work. ¿Can you do a some video whit the process in the new version?

**Comment by amottier** [comment]
Hi thanks for reporting this issue.

Actually example are not yet ported to version 7. I will try to update them as soon as I can.

**Comment by amottier** [comment]
I upload a new version of the example for Bonita BPM 7.0.2 Community (can also be used with Subscription edtion).

Issue is now fixed.
